WINDOW_SIZE = 2
MAX_SEQ_NO = 2*WINDOW_SIZE

SERVER_MAX_RETRIES = 10
SERVER_RECV_TIMEOUT = 1.0
SERVER_TIMER_THREAD_TIMEOUT = 1.0
SERVER_FILE_NOT_FOUND = 5
SERVER_END_PACKET = 2
SERVER_END_ABNORMAL = 3
SERVER_BUFFER_SIZE = 4096

CLIENT_MAX_RETRIES = 10
CLIENT_REQUEST_RETRIES = 2
CLIENT_RECV_TIMEOUT = 0.4
CLIENT_BUFFER_SIZE = 4096

CLIENT_MAIN_SERV_TIMEOUT = 5.0
CLIENT_MAIN_SERV_RETRIES = 10
CLIENT_MAIN_SERV_HB_RETRIES = 4

DATA_PAYLOAD_SIZE = CLIENT_BUFFER_SIZE - 2
DATA_PACKET = 0
DATA_ACK = 1

END_CONNECTION_ACK = 4
